---
name: 🛠 Continuous Integration / DevOps
about: Improve or update workflows or other automation
title: '[CI]'
labels: 'area/ci'
assignees: ''
---
#### Current Behavior
<!-- A brief description of what the problem is. (e.g. I need to be able to...) -->

#### Desired Behavior
<!-- A brief description of what you expected to happen. -->

#### Implementation
<!-- Specifics on the approach to fulfilling the feature request. -->

#### Acceptance Tests
<!-- Stipulations of functional behavior or non-functional items that must be in-place in order for the issue to be closed. -->

#### Reference:
- [Meshery Build & Release Strategy](https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#)
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
